### ISSUE TITLE
Would you be interested in supporting phoenix_live_dashboard?

### ISSUE THREAD

**Issue by josevalim** [pawurb/ecto_psql_extras#1]
Hi @pawurb! Thanks for the extremely useful repo!

Over the last weeks @alexcastano has been working on custom pages for the [Phoenix Live Dashboard](https://github.com/phoenixframework/phoenix_live_dashboard). Our main goal is to support something like `ecto_psql_extras`, but directly from the browser.

Now that the foundational work is done, we are discussing where to integrate the functionality. One approach that came to mind is to add the functionality directly here. Would you be interested in adding support for the Phoenix Live Dashboard in `ecto_psql_extras`? `phoenix_live_dashboard` would become an optional dependency. The amount of work necessary is also minimal, you can see [the page itself here](https://github.com/phoenixframework/phoenix_live_dashboard/pull/191/files#diff-c29dfb3c33ce083ab9c622f9a083c89d) - where the name of columns could probably be defined alongside each query in this repo and the all possible queries could also be made public.

Please let us know what you think, we will be glad to submit a PR! :)

**Comment by pawurb** [comment]
Hi @josevalim glad to hear you find the project useful.

Sure, I'm totally for simplifying the integration. Feel free to submit all the necessary changes, I'll be happy to accept them.

**Comment by pawurb** [comment]
As discussed in #2 I think it will be simpler for @alexcastano to work in his own repo and only include this one as dependency. I'll close the issue.
