### ISSUE TITLE
Outliers and Calls queries broken on PostgreSQL 13

### ISSUE THREAD

**Issue by dmarkow** [pawurb/ecto_psql_extras#14]
PostgreSQL 13 has removed `total_time` from `pg_stat_statements` and replaced it with `total_exec_time` (https://www.postgresql.org/docs/13/pgstatstatements.html), so any queries using `total_time` are raising exceptions so now the Outliers and Calls queries aren't functioning properly:

```
Server: localhost:4000 (http)
Request: GET /dashboard/nonode%40nohost/api_repo_info?nav=outliers
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42703 (undefined_column) column "total_time" does not exist

    query: /* 10 queries that have longest execution time in aggregate */

SELECT query AS query,
interval '1 millisecond' * total_time AS exec_time,
(total_time/sum(total_time) OVER()) AS prop_exec_time,
calls,
interval '1 millisecond' * (blk_read_time + blk_write_time) AS sync_io_time
FROM pg_stat_statements WHERE userid = (SELECT usesysid FROM pg_user WHERE usename = current_user LIMIT 1)
ORDER BY total_time DESC
LIMIT 10;

        (ecto_sql 3.5.1) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_psql_extras 0.3.2) lib/ecto_psql_extras.ex:53: EctoPSQLExtras.query/3
```

I would submit a PR but I'm not sure how to detect the PostgreSQL version during a query so `total_time` can still be used for versions 12 and lower.

**Comment by pawurb** [comment]
Hi. Thanks for spotting, I did not use PG 13 yet. 

I guess you can detect version from SQL like that: 

```sql
SELECT version() like 'PostgreSQL 13%';
```

followed by `CASE` statement it might do the trick, but I'm not sure, never tried something like that before. Maybe detecting PG version on Elixir level and changing the query string dynamically would be easier? 

If different SQL versions will be handled differently I guess we should add CI tests covering it. I'm not sure if GitHub actions support different runtime environments, eg. for Ruby version of this project I use CircleCI and it allows choosing Docker containers with different PG versions.  https://github.com/pawurb/ruby-pg-extras/blob/master/.circleci/config.yml

**Comment by dmarkow** [comment]
It actually seems that pg_stat_statements has its own version number, so we would want to detect version 1.7 or older to use the old column, and version 1.8 and newer for the newer column:

```
db=# SELECT * FROM pg_available_extensions WHERE name = 'pg_stat_statements';
        name        | default_version | installed_version |                                comment                                 
--------------------+-----------------+-------------------+------------------------------------------------------------------------
 pg_stat_statements | 1.8             | 1.8               | track planning and execution statistics of all SQL statements executed
```
