### ISSUE TITLE
Allow configuration to not log query

### ISSUE THREAD

**Issue by dbernheisel** [pawurb/ecto_psql_extras#28]
Heyo 👋 thanks for putting this together.

I have some regular tasks running that query the health of a database using this library, and some of the SQL is pretty long. The result being that every x seconds, all this SQL can get logged. In my case, every 10 seconds I get ~50 lines logged. I'd like to make this unlogged.

Is there a way to configure the call to not log?

For example, `EctoPSQLExtras.query(:extensions, YourApp.Repo, log: false)`

Right now, it allows arguments to adjust the sql, but not the options to the underlying repo.query.

https://github.com/pawurb/ecto_psql_extras/blob/537a328753cfb1d5d3a80f1865d77ddfa3930e19/lib/ecto_psql_extras.ex#L104-L119

I'll be happy to contribute a PR.

**Comment by pawurb** [comment]
Hi. Great idea. I was checking it out before, but did not find an easy way to disable it per query. In tests I've added:

```
Logger.configure([level: :info])
```

to disable it globally but it wouldn't work in production. I'm looking forward to PR if you know how to add this feature. BTW I'd prefer the output to be silenced by default.
