### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by djgoku** [pawurb/ecto_psql_extras#32]
When working on this PR https://github.com/pawurb/ecto_psql_extras/pull/31 and running tests locally. I had to connect to each containers database and run `CREATE DATABASE ecto_psql_extras`. Should I just add a comment to the `README.md` about having to create the database manually to get the tests to pass? Or did I miss a step?

**Comment by pawurb** [comment]
@djgoku database should be created automatically when starting the container for the first time.
