### ISSUE TITLE
Relax postgrex requirement

### ISSUE THREAD

**Issue by princemaple** [pawurb/ecto_psql_extras#54]
Hi,

There was a v0.19.0 release of postgrex. I found that ecto_sql uses this requirment `{:postgrex, "~> 0.16 or ~> 1.0", optional: true}`. I think `ecto_psql_extras` can use something similar, without the `optional` part.

This would save you from having to bump this every time a minor release comes out. What do you think?

Cheers.

**Comment by pawurb** [comment]
Thanks, for a suggestion. Can you prepare a pr?

**Comment by pawurb** [comment]
Resolved by #55
