### ISSUE TITLE
How about returning integer for sizes?

### ISSUE THREAD

**Issue by happysalada** [pawurb/ecto_psql_extras#6]
this package has been integrated by phoenix_live_dashboard and the result is great!

One problem is that returning string data for size makes it harder to sort by size.
here is an example in the code base https://github.com/pawurb/ecto_psql_extras/blob/master/lib/queries/index_size.ex#L10
See https://github.com/phoenixframework/phoenix_live_dashboard/issues/204 for more details.

Would it make sense to return integer data for sizes and let the consumer of this library format those?
Or if you want to be more flexible enable passing a parameter to be able to chose the format? (string or integer?)

Let me know if I'm being too vague.

**Comment by josevalim** [comment]
PR is sent here: #7

**Comment by pawurb** [comment]
#7 was merged and released as 0.3.0
